server:
  port: 8080

spring:
  application:
    name: jinchi
  thymeleaf:
    mode: XHTML
    cache: false
    prefix: classpath:/templates
  profiles:
    active: dev
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 1000Mb